# Generated by Django 4.1 on 2024-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='qtd_diaria',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='qtd_dias_pgto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='total_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='unidade_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
