# Generated by Django 4.1 on 2024-06-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_escala_qtd_diaria_alter_escala_qtd_dias_pgto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='area',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='tipo',
        ),
    ]
