# Generated by Django 4.1 on 2024-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_colaborador_area_remove_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
