# Generated by Django 4.1 on 2024-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_colaborador_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='name',
            new_name='colaborador_name',
        ),
        migrations.RenameField(
            model_name='escala',
            old_name='area',
            new_name='id_area',
        ),
        migrations.RenameField(
            model_name='escala',
            old_name='cargo',
            new_name='id_cargo',
        ),
        migrations.RenameField(
            model_name='escala',
            old_name='evento',
            new_name='id_evento',
        ),
        migrations.AddField(
            model_name='escala',
            name='alimentacao_fds_qtd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='alimentacao_fds_un',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='alimentacao_semana_qtd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='alimentacao_semana_un',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='alimentacao_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='companhia_aerea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='hora_ida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='hora_volta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='loc_voo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='meio_transporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='name_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='nome_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='nome_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='nome_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='passagem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='saida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='valor_mobilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='valor_passagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
