# Generated by Django 4.1 on 2024-06-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_escala_colaborador_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='name_id',
            new_name='id_colaborador',
        ),
    ]
