# Generated by Django 4.1 on 2024-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_id_escala_id_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='unidade_diaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
