# Generated by Django 4.1 on 2024-06-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_escala_unidade_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='qtd_dias_pgto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
