# Generated by Django 4.1 on 2024-06-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_escala_qtd_dias_pgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='qtd_dias_pgto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
