# Generated by Django 4.1 on 2024-06-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_escala_id_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='id_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.origem'),
        ),
    ]
