# Generated by Django 4.1 on 2024-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_escala_id_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='valor_deslocamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
