# Generated by Django 4.1 on 2024-06-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_escala_status_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='status_fase2',
            field=models.CharField(blank=True, default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='status_fase3',
            field=models.CharField(blank=True, default='PENDENTE', max_length=100, null=True),
        ),
    ]
