# Generated by Django 4.1 on 2024-06-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_escala_id_area_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area'),
        ),
    ]
