# Generated by Django 4.1 on 2024-06-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_realizado_r_hora_ida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='id_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.evento'),
        ),
    ]
