# Generated by Django 4.1 on 2024-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_escala_id_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='id_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
