# Generated by Django 4.1 on 2024-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_escala_sugestao_hora_ida_escala_sugestao_hora_volta'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='data_ida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escala',
            name='data_volta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
